name = "master-debater"
main = "src/worker.ts"
compatibility_date = "2023-05-18"
node_compat = true

# PRODUCTION
[env.production]
name = "debateai"
workers_dev = false

[env.production.vars]
ENVIRONMENT = "production"
SUPABASE_URL = "https://ndtxtzhxrwcowynlbaez.supabase.co"
FE_URL = "https://debateai.org"