name = "master-debater"
main = "src/worker.ts"
compatibility_date = "2023-05-18"
node_compat = true

[vars]
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"
SUPABASE_URL = "http://localhost:54321"

# PRODUCTION
[env.production]
name = "debateai"
routes = [{ pattern = "debateai.jawn.workers.dev", custom_domain = true, zone_name = "debateai.jawn.workers.dev" }]
workers_dev = false
vars = { ENVIRONMENT = "production", SUPABASE_URL = "https://ndtxtzhxrwcowynlbaez.supabase.co" }